engine.js
html.js
kni.js
kni.json
kni.usage
package-lock.json
template.js
verify.js

Add standalone HTML builder

---

CHANGE.md
HACKNI.md
MANUAL.md
describe.js
document.js
engine-test.js
engine.js
evaluate.js
examples/read.kni
grammar.js
kni.js
readline.js
story.js
tests/handler.1
tests/handler.kni
tests/read.1
verify.js

In response to #6 and #10.
Further work needed to support reading input with the included web console
implementation.

Add support for reading string input

---

README.md

- new major version for install instructions
- at least 2 spelling errors; one of them may have been a choice

Fix minor readme issues

---

MANUAL.md
evaluate.js

Branching out from my reading of the fethcing manual:
- of the floor/ceil/round trifecta, only one of them was actually as advertised
- document the power operator
- drop a copy-past-o from manhattan distance
- mark unused scope args, so that tsc shuts up

Eval fixes

---

grammar.js
html.js
index.js
kni.js
outline-lexer-test.js
template.js

Initial code cleanup done while addressing pre-tsconfig tsserver
feedback; less dependency, less problems.

Drop unused imports throughout

---

describe.js
document.js
engine-test.js
engine.js
grammar.js
inline-lexer.js
story.js
verify.js

- drop unused var from Ask.next
- drop unused self from constructor
- sunder many unused function args
- unused space pattern in inline-lexer

Drop unused variables throughout

---

engine.js

Makes the engine not depend on, essentially, its compiler to bootstrap its machine code.
Also eases an upcoming refactor of how all those instruction build functions work.

engine: decouple from story builder

---

CHANGE.md
package-lock.json
package.json

Redo of #24 now against a v4 branch

Release v4.0.3 to eliminate unpm references

---

console.js
document.js
engine.js
excerpt.js
grammar.js
inline-lexer-test.js
inline-lexer.js
outline-lexer-test.js
outline-lexer.js
parser.js
readline.js
scanner.js
scope.js
story.js
verify.js
wrapper.js

This was the most pervasive pre-type-checking concern flagged by tsserver.
While technically a CodeLens suggestion, and not actually a tsc blocker for type checking, this eliminates the most major source of $EDITOR level friction, while also generally improving code layout and grouping from a modern standpoint.

Classify all the things

---

package-lock.json
package.json

...besides, you're spelling it wrong: it's O-pen, not oh-Pee-ehn

Switch to open (opn deprecated)

---

engine.js
inline-lexer-test.js
inline-lexer.js
outline-lexer-test.js
outline-lexer.js
parser.js
scanner.js

A nice post-classification cleanup that's possible

Hoist pipeline stage debug flags

---

package-lock.json
package.json

Drop json-diff dev dep

---

excerpt.js
verify.js

As required by eslint:recommended towards #15

Mark empty blocks

---

inline-lexer.js

Because var scope hoisting ; because eslint:recommended gate towards #15

inline-lexer: convert all var to const/let

---

grammar.js

Use modern const/let and for-of because eslint:recommended gate towards #15

Varify and loopify the grammar module

---

template.js

- switch all vars to const/let
- drop conditional assignments
- reflow to clarify scope extants
- use arrow function callbacks
- hoist anonymous handler object, with simple methods decls
Originally motivated by eslint:recommended gate towards #15, but I have an upcoming further refactor circa the newly hoisted handler object for after this

template: modernize and harden

---

template.js

While complying eslint:recommended towards #15
Non-blocking, but seems an improvement on extensibility and reliability
One could imagine further positioning the latent handler object for more application specific integration/customization

Improvements made to template handler

---

.eslintrc.json

Use eslint:recommended base (modulo sundered-vars)

---

.nycrc.json
kni-test.js
kni.js
package-lock.json
package.json
test.js

Everything that has gone before was *so* *close* to a full command entry integration test
Not yet passing in compiled JSON mode, but the base case works

Add a kni command integration test

---

inline-lexer.js

Also fixed a latent bug circa next/flush

inline-lexer: ts-check
